sudo: false
language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
env:
  global:
    - secure: "Z562s7HN8ZRzPU8C01Tw5+fMmmZInl2UCdGP1wAzibcBnMWQGWdZX3WC9Wh9thIRQ9o/aUbvRjW8OHCUu7yVzkMRUUMjZHbpfM+AaZf7D03MWPZSOYK9uht/ninmcHsnEulPm15vCsnZRXSObCmWXqTfvxmUO5fDi4B4jE8Sb4o="
    - secure: "YoVx2hxlcG7W9IY2607pQ/4EwKYEgq97CY11NopLoP8y6fU2KuzMeSg8SqPbiDQ65HKLOHtFIpexPH2/7imggteQ9EkmQS4EtZsQgdQfounyllzbggy2uTJ6+GEYixVDsJ41W0PYXFgZKgGBA2Y2lGr93nVUWk2lnxRkiD4vgzg="
addons:
  sauce_connect: true
